[project]
name = 'bob-leader'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.burn-pepe-faktory]
path = 'contracts/burn-pepe-faktory.clar'
clarity_version = 3
epoch = 3.1

[contracts.tokensoft-token-v4k68639zxz]
path = 'contracts/tokensoft-token-v4k68639zxz.clar'
clarity_version = 3
epoch = 3.1

[contracts.bob-bonus-faktory]
path = 'contracts/bob-bonus-faktory.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
